---
title: Dojo
email: ""
description: People-First
chronicles:
  - label: Culture
    link: "https://www.youtube.com/watch?v=5TWsIeeYu7k"
  - label: Contribution
    link: "https://community.sap.com/t5/open-source-blogs/innersource-first-contribution-explored/ba-p/13644916"
  - label: Agile
    link: "https://community.sap.com/t5/sap-for-higher-education-and-research-blogs/omg-i-am-a-new-product-owner-help/ba-p/13553971"
  - label: DevOps
    link: "https://www.sumologic.com/blog/how-sap-built-a-dojo-community-of-practice-to-support-a-cultural-shift-to-devops/"
  - label: DataOps
    link: "https://community.sap.com/t5/sap-for-higher-education-and-research-blogs/from-challenges-to-transformation-the-data-services-organization-dojo-tale/ba-p/13646867"
  - label: Senpai
    link: "https://community.sap.com/t5/open-source-blogs/from-learner-to-leader-the-power-of-senpai/ba-p/13662823"
  - label: Circles
    link: "https://community.sap.com/t5/sap-for-higher-education-and-research-blogs/dojo-mindset-and-agile-circles-the-socratic-method-practically-applied-to/ba-p/13678600"

homepageIntroduction:
  tagline: People-First Insightful Learning Circles ("Third Places")
  pitch: In our peer-supported community circles, people learn to be empowered to navigate unexpected change, confusion, chaos and feelings of being stuck by shedding limiting beliefs and tendencies.  This process helps them feel safer, more powerful and adaptable.  Through practices like Compassionate Conflict and Systems Thinking Reflex, we unlock insightful learning that fosters resilience, robustness and relaxed alertness.  For example, conflict transforms from combat to an engagement akin to sports, dance or music.  Our methods lead to Metashifts—positive shifts in perception and lived experience—that help drive innovation, flow and profit in business. And, our deeper passion lies in helping people in any realm, personal or professional, to create a more compassionate world.

beltLevels:
  - label: White level - Appeal
    value: white
    competences:
      - Initial exposure, like noticing someone is riding a bicycle
      - Sets an intention to explore an unfamiliar domain
      - '<a href="./Orientation-Request">Orientation - Start your journey by putting on your first belt</a>'
  - label: Green level - Aware
    value: green
    competences:
      - Abstract understanding, like observing a friend ride a bicycle
      - Able to work with basic concepts fluidly in conversation
      - '<a href="./Belt-Request">Belt Claim - Demonstrate grasp of key metaphors, motivations and mindsets</a>'
  - label: Red level - Action
    value: red
    competences:
      - Action-based understanding, like riding a bicycle at first, falling down frequently
      - Demonstrated applied action using a new skill supported by peers
      - '<a href="./Belt-Request">Belt Claim - Demonstrate competence to apply skill going forward with autonomy and inclusiveness</a>'
  - label: Black level - Acceleration
    value: black
    competences:
      - Embodiment, like pedaling a bicycle fast and hard, learning safely when falling
      - Demonstrated commitment to helping others explore the domain
      - '<a href="./Belt-Request">Belt Claim - Demonstrate scaled action illustrating benefit for your home group</a>'

learningGuidance:
  - Explore the concepts and exercises below
  - Summarize the key points in writing at each step and circle back as you progress
  - Have dialog with peers to test and deepen understanding

domains:
  - Mindset

circles:
  - label: Dojo Circle
    url: https://circle.dojo.center
    times: 
      - Fridays at 8 AM CT (13:00 UTC / 14:00 UTC)

sensei:
  - label: Michael Basil 
    url: https://www.linkedin.com/in/michaelrbasil
    details:
      - Regular attendee of Friday Dojo Circle
      - Available for open networking conversations
      - Private coaching / consultation inquiries welcome
  - label: Bill Westfall 
    url: https://www.linkedin.com/in/bill-westfall-3268494
    details:
      - Regular attendee of Friday Dojo Circle

community:
  - link: Members
    icon: users
  - link: Stats
    icon: pie-chart

requests:
  - Belt-Request
  - Orientation-Request

# Blog settings
show_excerpts: false

# URL settings
homeUrl: "https://dojo.center"
feedbackUrl: "https://github.com/dojo-center/dojo-center.github.io/issues/new"

repository: "dojo-center/dojo-center.github.io"
repositoryUrl: "https://github.com/dojo-center/dojo-center.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
